version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python main.py
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python tests.py
  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - run: echo "Deploying to production server"
  sonar-scan:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Install AND run SonarScanner CLI (Linux)
          command: |
            export SONAR_SCANNER_VERSION=7.0.2.4839
            export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux-x64
            curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux-x64.zip
            unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
            export PATH=$SONAR_SCANNER_HOME/bin:$PATH
            
            sonar-scanner \
            -Dsonar.login=$SONAR_TOKEN
            -Dsonar.projectKey=demo1 \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://34.238.136.19:9000
            # sonar-scanner \
            # -Dsonar.projectKey=demo1 \
            # -Dsonar.sources=. \
            # -Dsonar.host.url=http://34.238.136.19:9000
            # -Dsonar.login=$SONAR_TOKEN


workflows:
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build 
      - sonar-scan:
          requires:
            - test
      - deploy:
          requires:
            - sonar-scan
          filters:
            branches:
              only: main
